#  ------------------------------
# |        HuskChat Config      |
# |    Developed by William278  |
#  ------------------------------
# Configuration guide: https://github.com/WiIIiam278/HuskChat/wiki
# To modify individual message locales, see the messages file.

# General options. Default channel should match one of the channels below.
language: 'en-gb'
default_channel: global
channel_log_format: '[CHAT] [%channel%] %sender%: '
channel_command_aliases: # Must contain at least one item; the first being the primary alias of the command
  - /channel
  - /c

# Chat channel configuration.
# - You can edit the default channels and make your own if you would like.
# - Channels that have permissions set require them to send and receive messages respectively.
channels:
  local:
    format: '%fullname%&r&f: '
    broadcast_scope: LOCAL
    log_to_console: true
    shortcut_commands:
      - /local
      - /l
  global:
    format: '&#00fb9a&[G]&r&f %fullname%&r&f: '
    broadcast_scope: GLOBAL
    log_to_console: true
    shortcut_commands:
      - /global
      - /g
    #restricted_servers: # Set where it is not possible to use this channel
    #  - minigame
  staff:
    format: '&e[Staff] %name%: &7'
    broadcast_scope: GLOBAL
    log_to_console: true
    filtered: false
    permissions:
      send: 'huskchat.channel.staff.send'
      receive: 'huskchat.channel.staff.receive'
    shortcut_commands:
      - /staff
      - /sc
  helpop:
    format: '&#00fb9a&[HelpOp] %name%: &7'
    broadcast_scope: GLOBAL
    log_to_console: true
    filtered: false
    permissions:
      receive: 'huskchat.channel.helpop.receive'
    shortcut_commands:
      - /helpop
      - /helpme

# Server Default Channel Configuration
# - Set a channel that the player will automatically be set to when changing servers
# - Players will still be able to switch channels and use /msg and /r unless you add servers to the restricted_servers list
#server_default_channels:
#  minigame: local

# Options for the /msg and /r commands
message_command:
  enabled: true
  msg_aliases:
    - /msg
    - /m
    - /tell
    - /whisper
    - /w
    - /pm
  reply_aliases:
    - /reply
    - /r
  log_to_console: true
  log_format: '[MSG] [%sender% -> %receiver%]: '
  format:
    inbound: '&#00fb9a&%name% &8â†’ &#00fb9a&You&8: &f'
    outbound: '&#00fb9a&You &8â†’ &#00fb9a&%name%&8: &f'
  #restricted_servers: # Set where /msg and /r cannot be used
  #  - hub

# Options for the /socialspy command
social_spy:
  enabled: true
  format: '&e[Spy] &7%sender_name% &8â†’ &7%receiever_name%:%spy_color% '
  socialspy_aliases:
    - /socialspy
    - /ss
# Options for the /localspy command
local_spy:
  enabled: true
  format: '&e[Spy] &7[%channel%] %name%&8:%spy_color% '
  localspy_aliases:
    - /localspy
    - /ls
  #excluded_local_channels: # Channels to exclude from local spying
  #  - local
# Options for the /broadcast command
broadcast_command:
  enabled: true
  broadcast_aliases:
    - /broadcast
    - /alert
  format: '&6[Broadcast]&e '
  log_to_console: true
  log_format: '[BROADCAST]: '

# Chat filter options
chat_filters:
  # Filters against IP addresses and links
  advertising_filter:
    enabled: true
  # Filters against CAPS use; specify the maximum % a message can contain capital letters
  caps_filter:
    enabled: true
    max_caps_percentage: 0.4
  # Filters against users sending messages too quickly (configure how many messages users can send over a period of seconds)
  spam_filter:
    enabled: true
    period_seconds: 4
    messages_per_period: 3
  # Filters against profanity using machine learning. Requires Python 3.8+ on the server with jep and alt-profanity-check installed.
  profanity_filter:
    enabled: false
    library_path: '' # Define a directory path for the jep library
    mode: AUTOMATIC # Filter rule - AUTOMATIC or TOLERANCE.
    tolerance: 0.78 # If using TOLERANCE mode, the algorithm will determine a profanity probability and compare with this to filter.
  repeat_filter:
    enabled: true
    previous_messages_to_check: 2
  # Filters against the use of non-ASCII (Unicode) characters
  ascii_filter:
    enabled: false

# Chat message replacer options
message_replacers:
  # Replaces text emoticons in messages with the correct emoji
  emoji_replacer:
    enabled: true
    case_insensitive: false
    emoji: # Emote character options: https://gist.githubusercontent.com/WiIIiam278/b74a6af6d9670350a60ad09d63b67169/raw/d8b596471c812eb2b68638469cb779d928bd733f/minecraft_unicode_characters.txt
      ':)': 'â˜º'
      ':smile:': 'â˜º'
      ':-)': 'â˜º'
      ':(': 'â˜¹'
      ':frown:': 'â˜¹'
      ':-(': 'â˜¹'
      ':fire:': 'ðŸ”¥'

# Version of the config file
config-version: 1